cp-zookeeper:
  enabled: true
  servers: 1
  persistence:
    enabled: false
  prometheus:
    jxm:
      enabled: false

cp-kafka:
  enabled: true
  brokers: 1
  configurationOverrides:
    "offsets.topic.replication.factor": "1"
    "default.replication.factor": 1
    "min.insync.replicas": 1
    "confluent.metrics.reporter.topic.replicas": 1
    "opts": "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf"
  persistence:
    enabled: false
  prometheus:
    jmx:
      enabled: false

cp-kafka-connect:
  enabled: false

cp-schema-registry:
  enabled: false

cp-kafka-rest:
  enabled: false

cp-ksql-server:
  enabled: false

cp-control-center:
  enabled: true
  configurationOverrides:
    "replication.factor": 1
  prometheus:
    jmx:
      enabled: false