apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-security-config
data:
  zookeeper_jaas.conf: |
    Server {
      org.apache.zookeeper.server.auth.DigestLoginModule required
      user_super="adminsecret"
      user_broker="brokersecret";
    };
